/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DataWow Concert Tickets API
 * RESTful API for free concert ticket reservation. Supports JWT authentication, role-based access (Admin/User), Redis caching, rate limiting, and Kafka-based concurrency control.
 * OpenAPI spec version: 1.0
 */
import type {
  AuthResponse,
  CancelResponse,
  Concert,
  ConcertWithStats,
  CreateConcertDto,
  LoginDto,
  RegisterDto,
  Reservation,
  ReservationPending,
  UserProfile,
  UserReservation
} from './model';

import { axiosInstance } from '../../lib/axios-instance';



  export const getDataWowConcertTicketsAPI = () => {
/**
 * Creates a new user account and returns a JWT token. Role is always "user".
 * @summary Register a new user
 */
const register = (
    registerDto: RegisterDto,
 ) => {
      return axiosInstance<AuthResponse>(
      {url: `/api/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerDto
    },
      );
    }
  
/**
 * Authenticates the user and returns a JWT token.
 * @summary Login with email and password
 */
const login = (
    loginDto: LoginDto,
 ) => {
      return axiosInstance<AuthResponse>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginDto
    },
      );
    }
  
/**
 * Returns the authenticated user's profile.
 * @summary Get current user profile
 */
const getProfile = (
    
 ) => {
      return axiosInstance<UserProfile>(
      {url: `/api/auth/me`, method: 'GET'
    },
      );
    }
  
/**
 * Returns all concerts with reservation stats. Cached in Redis (30s TTL).
 * @summary List all concerts
 */
const findAllConcerts = (
    
 ) => {
      return axiosInstance<ConcertWithStats[]>(
      {url: `/api/concerts`, method: 'GET'
    },
      );
    }
  
/**
 * Creates a new concert listing.
 * @summary Create a concert (Admin)
 */
const createConcert = (
    createConcertDto: CreateConcertDto,
 ) => {
      return axiosInstance<Concert>(
      {url: `/api/concerts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createConcertDto
    },
      );
    }
  
/**
 * @summary Get a single concert
 */
const findOneConcert = (
    id: string,
 ) => {
      return axiosInstance<Concert>(
      {url: `/api/concerts/${id}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Delete a concert (Admin)
 */
const deleteConcert = (
    id: string,
 ) => {
      return axiosInstance<void>(
      {url: `/api/concerts/${id}`, method: 'DELETE'
    },
      );
    }
  
/**
 * Reserves a seat for the authenticated user.
 * @summary Reserve a seat (User)
 */
const reserveSeat = (
    concertId: string,
 ) => {
      return axiosInstance<Reservation | ReservationPending>(
      {url: `/api/reservations/${concertId}`, method: 'POST'
    },
      );
    }
  
/**
 * @summary Cancel a reservation (User)
 */
const cancelReservation = (
    concertId: string,
 ) => {
      return axiosInstance<CancelResponse>(
      {url: `/api/reservations/${concertId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary My reservation history (User)
 */
const getMyReservations = (
    
 ) => {
      return axiosInstance<UserReservation[]>(
      {url: `/api/reservations/me`, method: 'GET'
    },
      );
    }
  
return {register,login,getProfile,findAllConcerts,createConcert,findOneConcert,deleteConcert,reserveSeat,cancelReservation,getMyReservations}};
export type RegisterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataWowConcertTicketsAPI>['register']>>>
export type LoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataWowConcertTicketsAPI>['login']>>>
export type GetProfileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataWowConcertTicketsAPI>['getProfile']>>>
export type FindAllConcertsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataWowConcertTicketsAPI>['findAllConcerts']>>>
export type CreateConcertResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataWowConcertTicketsAPI>['createConcert']>>>
export type FindOneConcertResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataWowConcertTicketsAPI>['findOneConcert']>>>
export type DeleteConcertResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataWowConcertTicketsAPI>['deleteConcert']>>>
export type ReserveSeatResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataWowConcertTicketsAPI>['reserveSeat']>>>
export type CancelReservationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataWowConcertTicketsAPI>['cancelReservation']>>>
export type GetMyReservationsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataWowConcertTicketsAPI>['getMyReservations']>>>
