/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DataWow Concert Tickets API
 * RESTful API for free concert ticket reservation. Supports JWT authentication, role-based access (Admin/User), Redis caching, rate limiting, and Kafka-based concurrency control.
 * OpenAPI spec version: 1.0
 */

export interface Concert {
  id?: string;
  name?: string;
  description?: string;
  totalSeats?: number;
  createdAt?: string;
  updatedAt?: string;
}
