/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DataWow Concert Tickets API
 * RESTful API for free concert ticket reservation. Supports JWT authentication, role-based access (Admin/User), Redis caching, rate limiting, and Kafka-based concurrency control.
 * OpenAPI spec version: 1.0
 */
import type { ReservationStatus } from './reservationStatus';

export interface Reservation {
  id?: string;
  userId?: string;
  concertId?: string;
  status?: ReservationStatus;
  /** @nullable */
  rejectedReason?: string | null;
  createdAt?: string;
  /** @nullable */
  cancelledAt?: string | null;
}
