/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DataWow Concert Tickets API
 * RESTful API for free concert ticket reservation. Supports JWT authentication, role-based access (Admin/User), Redis caching, rate limiting, and Kafka-based concurrency control.
 * OpenAPI spec version: 1.0
 */

export type ReservationStatus = typeof ReservationStatus[keyof typeof ReservationStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReservationStatus = {
  pending: 'pending',
  reserved: 'reserved',
  rejected: 'rejected',
  cancelled: 'cancelled',
} as const;
