/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DataWow Audit Service API
 * Audit log microservice — provides admin audit trail of all system actions.
 * OpenAPI spec version: 1.0
 */
import type {
  AuditLogPaginatedResponse,
  GetAuditLogsParams,
  HealthResponse
} from './model';

import { auditAxiosInstance } from '../../lib/axios-instance';



  export const getDataWowAuditServiceAPI = () => {
/**
 * Returns paginated audit trail of all admin actions.
 * @summary Get admin audit logs
 */
const getAuditLogs = (
    params?: GetAuditLogsParams,
 ) => {
      return auditAxiosInstance<AuditLogPaginatedResponse>(
      {url: `/api/audit-logs`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary Health check
 */
const healthCheck = (
    
 ) => {
      return auditAxiosInstance<HealthResponse>(
      {url: `/api/health`, method: 'GET'
    },
      );
    }
  
return {getAuditLogs,healthCheck}};
export type GetAuditLogsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataWowAuditServiceAPI>['getAuditLogs']>>>
export type HealthCheckResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDataWowAuditServiceAPI>['healthCheck']>>>
