/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DataWow Audit Service API
 * Audit log microservice — provides admin audit trail of all system actions.
 * OpenAPI spec version: 1.0
 */
import type { AuditLogEntry } from './auditLogEntry';

export interface AuditLogPaginatedResponse {
  data?: AuditLogEntry[];
  total?: number;
  page?: number;
  limit?: number;
}
