/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DataWow Audit Service API
 * Audit log microservice — provides admin audit trail of all system actions.
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type AuditLogEntryPerformer = {
  id?: string;
  email?: string;
  fullName?: string;
} | null;
