/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DataWow Audit Service API
 * Audit log microservice — provides admin audit trail of all system actions.
 * OpenAPI spec version: 1.0
 */
import type { AuditLogEntryDetails } from './auditLogEntryDetails';
import type { AuditLogEntryPerformer } from './auditLogEntryPerformer';

export interface AuditLogEntry {
  id?: string;
  action?: string;
  entity?: string;
  /** @nullable */
  entityId?: string | null;
  /** @nullable */
  details?: AuditLogEntryDetails;
  performedBy?: string;
  createdAt?: string;
  /** @nullable */
  performer?: AuditLogEntryPerformer;
}
