/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DataWow Audit Service API
 * Audit log microservice — provides admin audit trail of all system actions.
 * OpenAPI spec version: 1.0
 */

export type GetAuditLogsParams = {
/**
 * Page number
 */
page?: number;
/**
 * Items per page (max 200)
 * @maximum 200
 */
limit?: number;
};
